In [1]:
import pandas as pd
from stock_selection_graph import create_and_compile_graph
from pathlib import Path
import numpy as np
import json
import os
from schemas import StockInfoAndResearch, StockSelectionState
from model_inference import obtain_inference_performance_to_date

In [2]:
with open("api_keys.json", "r", encoding="utf-8") as f:
    api_keys = json.load(f)["api_keys"][0]

os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGSMITH_API_KEY"] = api_keys["langsmith"]
os.environ["LANGSMITH_PROJECT"] = "portfolio_selection"

In [3]:
inference_results = pd.read_parquet("Data_01_04_2026/results/inference_predictions.parquet")
inference_performance_to_date = obtain_inference_performance_to_date(inference_results)

In [4]:
selected_stocks = [
    "NTSK",
    "INV",
    "MNTN",
    "CHA",
    "AGBK",
    "KLAR",
    "SSII",
    "BETA",
    "WOLF",
    "FLY",
    "EQPT",
    "WYFI",
    "OMDA",
    "TLX",
    "IBTA",
    "FIGR",
    "BBNX",
    "MANE",
    "LMRI",
    "PICS",
    "SAIL",
    "ANTA",
    "XZO",
    "ETOR",
    "PTRN",
    "AERO",
    "HTFL",
    "GLXY",
    "WLTH",
    "BLLN"
]


candidate_investments = inference_results[inference_results.ticker.isin(
    selected_stocks
) & (inference_results.calendardate == "2026-03-31")].sort_values('y_pred')

In [5]:
test_date = '2026-03-31'
TICKER_DATA_PATH = "Data_05_03_2026/SHARADAR_TICKERS.parquet"
ticker_data = pd.read_parquet(TICKER_DATA_PATH)

investments = candidate_investments[candidate_investments.calendardate == test_date]
candidate_investments = candidate_investments[candidate_investments.calendardate == test_date]
stocks_to_consider = candidate_investments.ticker.unique().tolist()

candidate_stocks = inference_results[
    (inference_results.calendardate == test_date ) & (inference_results.ticker.isin(stocks_to_consider))
].copy()

companies = ticker_data[
    ticker_data.isdelisted == "N"
][["ticker", "name", "companysite"]].drop_duplicates()

candidate_stocks = candidate_stocks.merge(companies)
sector_data = ticker_data[['ticker', 'sector']].drop_duplicates().dropna()
candidate_stocks = candidate_stocks.merge(sector_data, on='ticker', how='left')

candidate_stocks = candidate_stocks[[
    "ticker",
    "name",
    "sector",
    "companysite",
    "y_pred"
]].rename(
    columns={
        "y_pred": "prediction_pct_change"
    }
)

In [6]:
def get_input_state(
    candidate_stocks: pd.DataFrame,
    number_of_stocks_to_select: int = 20,
    back_test_date: str = None,
) -> StockSelectionState:
    candidate_stocks_clean = candidate_stocks.astype(object).where(
        pd.notna(candidate_stocks),
        None
    )
    candidate_stocks_dict = candidate_stocks_clean.to_dict(orient="records")
    candidate_stocks = [StockInfoAndResearch(**x) for x in candidate_stocks_dict]

    input_state = StockSelectionState(
        stocks=candidate_stocks,
        back_test_date=back_test_date,
        number_of_stocks_to_select=number_of_stocks_to_select
    )

    return input_state

input_state = get_input_state(candidate_stocks, 20)

In [8]:
graph = create_and_compile_graph()
response = graph.invoke(input_state)

In [9]:
selected_investments = candidate_investments[candidate_investments.ticker.isin([x.ticker for x in response['portfolio_selection'].selected_stocks])]
deselected_investments = candidate_investments[candidate_investments.ticker.isin([x.ticker for x in response['portfolio_selection'].excluded_stocks])]

In [11]:
response

{'stocks': [StockInfoAndResearch(ticker='AERO', name='GRUPO AEROMEXICO SAB DE CV', sector='Industrials', companysite='https://www.aeromexico.com/es-mx', prediction_pct_change=0.7239158749580383, research=None),
  StockInfoAndResearch(ticker='AGBK', name='AGI INC', sector='Financial Services', companysite='https://agibank.com.br', prediction_pct_change=1.233537197113037, research=None),
  StockInfoAndResearch(ticker='ANTA', name='ANTALPHA PLATFORM HOLDING CO', sector='Financial Services', companysite='https://www.antalpha.com', prediction_pct_change=0.7326064705848694, research=None),
  StockInfoAndResearch(ticker='BBNX', name='BETA BIONICS INC', sector='Healthcare', companysite='https://www.betabionics.com', prediction_pct_change=0.8297722935676575, research=None),
  StockInfoAndResearch(ticker='BETA', name='BETA TECHNOLOGIES INC', sector='Industrials', companysite='https://beta.team', prediction_pct_change=1.0719736814498901, research=None),
  StockInfoAndResearch(ticker='BLLN', name='BILLIONTOONE INC', sector='Healthcare', companysite='https://www.billiontoone.com', prediction_pct_change=0.6889353394508362, research=None),
  StockInfoAndResearch(ticker='CHA', name='CHAGEE HOLDINGS LTD', sector='Consumer Cyclical', companysite='https://chagee.com/en', prediction_pct_change=1.2857122421264648, research=None),
  StockInfoAndResearch(ticker='EQPT', name='EQUIPMENTSHARECOM INC', sector='Industrials', companysite='https://www.equipmentshare.com', prediction_pct_change=0.9999864101409912, research=None),
  StockInfoAndResearch(ticker='ETOR', name='ETORO GROUP LTD', sector='Financial Services', companysite='https://www.etoro.com', prediction_pct_change=0.7294036149978638, research=None),
  StockInfoAndResearch(ticker='FIGR', name='FIGURE TECHNOLOGY SOLUTIONS INC', sector='Financial Services', companysite='https://www.figure.com', prediction_pct_change=0.8461740612983704, research=None),
  StockInfoAndResearch(ticker='FLY', name='FIREFLY AEROSPACE INC', sector='Industrials', companysite='https://www.fireflyspace.com', prediction_pct_change=1.0232582092285156, research=None),
  StockInfoAndResearch(ticker='GLXY', name='GALAXY DIGITAL INC', sector='Financial Services', companysite='https://www.galaxy.com', prediction_pct_change=0.7095593810081482, research=None),
  StockInfoAndResearch(ticker='HTFL', name='HEARTFLOW INC', sector='Healthcare', companysite='https://www.heartflow.com', prediction_pct_change=0.7200798988342285, research=None),
  StockInfoAndResearch(ticker='IBTA', name='IBOTTA INC', sector='Technology', companysite='https://www.ibotta.com', prediction_pct_change=0.8702093958854675, research=None),
  StockInfoAndResearch(ticker='INV', name='INNVENTURE INC', sector='Financial Services', companysite='https://www.innventure.com', prediction_pct_change=1.361485481262207, research=None),
  StockInfoAndResearch(ticker='KLAR', name='KLARNA GROUP PLC', sector='Technology', companysite='https://www.klarna.com', prediction_pct_change=1.1819326877593994, research=None),
  StockInfoAndResearch(ticker='LMRI', name='LUMEXA IMAGING HOLDINGS INC', sector='Healthcare', companysite='https://www.lumexaimaging.com', prediction_pct_change=0.7779592275619507, research=None),
  StockInfoAndResearch(ticker='MANE', name='VERADERMICS INC', sector='Healthcare', companysite='https://www.veradermics.com', prediction_pct_change=0.8065634965896606, research=None),
  StockInfoAndResearch(ticker='MNTN', name='MNTN INC', sector='Technology', companysite='https://mountain.com', prediction_pct_change=1.3128361701965332, research=None),
  StockInfoAndResearch(ticker='NTSK', name='NETSKOPE INC', sector='Technology', companysite='https://www.netskope.com', prediction_pct_change=1.382552146911621, research=None),
  StockInfoAndResearch(ticker='OMDA', name='OMADA HEALTH INC', sector='Healthcare', companysite='https://www.omadahealth.com', prediction_pct_change=0.937030553817749, research=None),
  StockInfoAndResearch(ticker='PICS', name='PICS NV', sector='Technology', companysite='https://www.picpay.com', prediction_pct_change=0.7438918352127075, research=None),
  StockInfoAndResearch(ticker='PTRN', name='PATTERN GROUP INC', sector='Consumer Cyclical', companysite='https://www.pattern.com', prediction_pct_change=0.7279417514801025, research=None),
  StockInfoAndResearch(ticker='SAIL', name='SAILPOINT INC', sector='Technology', companysite='https://www.sailpoint.com', prediction_pct_change=0.7374891042709351, research=None),
  StockInfoAndResearch(ticker='SSII', name='SS INNOVATIONS INTERNATIONAL INC', sector='Healthcare', companysite='https://ssinnovations.com', prediction_pct_change=1.1149864196777344, research=None),
  StockInfoAndResearch(ticker='TLX', name='TELIX PHARMACEUTICALS LTD', sector='Healthcare', companysite='https://telixpharma.com', prediction_pct_change=0.8992024064064026, research=None),
  StockInfoAndResearch(ticker='WLTH', name='WEALTHFRONT CORP', sector='Technology', companysite='https://www.wealthfront.com', prediction_pct_change=0.7063301205635071, research=None),
  StockInfoAndResearch(ticker='WOLF', name='WOLFSPEED INC', sector='Technology', companysite='https://www.wolfspeed.com', prediction_pct_change=1.0444366931915283, research=None),
  StockInfoAndResearch(ticker='WYFI', name='WHITEFIBER INC', sector='Technology', companysite='https://www.whitefiber.com', prediction_pct_change=0.9758886098861694, research=None),
  StockInfoAndResearch(ticker='XZO', name='EXZEO GROUP INC', sector='Financial Services', companysite='https://www.exzeo.com', prediction_pct_change=0.7300814390182495, research=None)],

In [12]:
import json
from pathlib import Path
from pydantic import BaseModel

def _default(obj):
    if isinstance(obj, BaseModel):
        return obj.model_dump()
    raise TypeError(f"Not serializable: {type(obj)}")

out_path = Path("Data_01_04_2026/results/graph_response.json")
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(json.dumps(response, default=_default, indent=2))

845893

In [15]:
candidate_stocks

,ticker,name,sector,companysite,prediction_pct_change
0,AERO,GRUPO AEROMEXICO SAB DE CV,Industrials,https://www.aeromexico.com/es-mx,0.723916
1,AGBK,AGI INC,Financial Services,https://agibank.com.br,1.233537
2,ANTA,ANTALPHA PLATFORM HOLDING CO,Financial Services,https://www.antalpha.com,0.732606
3,BBNX,BETA BIONICS INC,Healthcare,https://www.betabionics.com,0.829772
4,BETA,BETA TECHNOLOGIES INC,Industrials,https://beta.team,1.071974
5,BLLN,BILLIONTOONE INC,Healthcare,https://www.billiontoone.com,0.688935
6,CHA,CHAGEE HOLDINGS LTD,Consumer Cyclical,https://chagee.com/en,1.285712
7,EQPT,EQUIPMENTSHARECOM INC,Industrials,https://www.equipmentshare.com,0.999986
8,ETOR,ETORO GROUP LTD,Financial Services,https://www.etoro.com,0.729404
9,FIGR,FIGURE TECHNOLOGY SOLUTIONS INC,Financial Services,https://www.figure.com,0.846174
10,FLY,FIREFLY AEROSPACE INC,Industrials,https://www.fireflyspace.com,1.023258
11,GLXY,GALAXY DIGITAL INC,Financial Services,https://www.galaxy.com,0.709559
12,HTFL,HEARTFLOW INC,Healthcare,https://www.heartflow.com,0.720080
13,IBTA,IBOTTA INC,Technology,https://www.ibotta.com,0.870209
14,INV,INNVENTURE INC,Financial Services,https://www.innventure.com,1.361485
15,KLAR,KLARNA GROUP PLC,Technology,https://www.klarna.com,1.181933
16,LMRI,LUMEXA IMAGING HOLDINGS INC,Healthcare,https://www.lumexaimaging.com,0.777959
17,MANE,VERADERMICS INC,Healthcare,https://www.veradermics.com,0.806563
18,MNTN,MNTN INC,Technology,https://mountain.com,1.312836
19,NTSK,NETSKOPE INC,Technology,https://www.netskope.com,1.382552
20,OMDA,OMADA HEALTH INC,Healthcare,https://www.omadahealth.com,0.937031
21,PICS,PICS NV,Technology,https://www.picpay.com,0.743892
22,PTRN,PATTERN GROUP INC,Consumer Cyclical,https://www.pattern.com,0.727942
23,SAIL,SAILPOINT INC,Technology,https://www.sailpoint.com,0.737489
24,SSII,SS INNOVATIONS INTERNATIONAL INC,Healthcare,https://ssinnovations.com,1.114986
25,TLX,TELIX PHARMACEUTICALS LTD,Healthcare,https://telixpharma.com,0.899202
26,WLTH,WEALTHFRONT CORP,Technology,https://www.wealthfront.com,0.706330
27,WOLF,WOLFSPEED INC,Technology,https://www.wolfspeed.com,1.044437
28,WYFI,WHITEFIBER INC,Technology,https://www.whitefiber.com,0.975889
29,XZO,EXZEO GROUP INC,Financial Services,https://www.exzeo.com,0.730081

In [14]:
selected_investments

,ticker,calendardate,y_pred,close,close_max,marketcap,marketcap_quantile
4657,BLLN,2026-03-31,0.688935,78.94,130.18,3.096257e+09,176145803.0
7063,GLXY,2026-03-31,0.709559,18.45,42.86,8.536775e+09,176145803.0
7776,HTFL,2026-03-31,0.720080,24.33,39.91,2.184250e+09,176145803.0
12027,PTRN,2026-03-31,0.727942,12.43,18.40,1.911071e+09,176145803.0
6050,ETOR,2026-03-31,0.729404,30.03,75.97,2.541053e+09,176145803.0
12782,SAIL,2026-03-31,0.737489,13.24,25.70,6.957334e+09,176145803.0
11619,PICS,2026-03-31,0.743892,10.45,18.00,1.590039e+09,176145803.0
9231,LMRI,2026-03-31,0.777959,8.60,18.53,7.659961e+08,176145803.0
9525,MANE,2026-03-31,0.806563,63.15,67.55,2.272157e+09,176145803.0
7933,IBTA,2026-03-31,0.870209,29.97,109.90,6.416272e+08,176145803.0
13662,TLX,2026-03-31,0.899202,9.57,20.93,2.605196e+09,176145803.0
11020,OMDA,2026-03-31,0.937031,12.57,26.78,8.279024e+08,176145803.0
14407,WYFI,2026-03-31,0.975889,11.91,39.13,4.667146e+08,176145803.0
5960,EQPT,2026-03-31,0.999986,20.37,34.63,6.049912e+09,176145803.0
6471,FLY,2026-03-31,1.023258,28.47,60.35,3.714094e+09,176145803.0
4440,BETA,2026-03-31,1.071974,14.70,36.80,4.955724e+09,176145803.0
8724,KLAR,2026-03-31,1.181933,13.09,45.48,1.016594e+10,176145803.0
3118,AGBK,2026-03-31,1.233537,7.27,12.00,1.510752e+09,176145803.0
9937,MNTN,2026-03-31,1.312836,8.80,31.47,7.564566e+08,176145803.0
10691,NTSK,2026-03-31,1.382552,8.49,25.79,3.398668e+09,176145803.0

In [8]:
comp = pd.concat(
    [
        selected_investments.sort_values('pct_change').pct_change_at_max_date.describe(),
        investments.pct_change_at_max_date.describe()
    ], axis=1
)

comp.columns = ['AI Filtered', 'Normal']
comp

       AI Filtered     Normal
count    20.000000  20.000000
mean      1.363858   2.092430
std       2.653755   3.998254
min      -0.359316  -0.702194
25%       0.331210   0.213362
50%       0.815797   0.793068
75%       1.601507   1.680216
max      12.209702  14.264052

In [39]:
inference_performance_to_date[
    (inference_performance_to_date.ticker.isin(deselected_investments.ticker))
    & (inference_performance_to_date.calendardate == test_date)
].pct_change_at_max_date.describe()

count    10.000000
mean      2.167170
std       4.495558
min      -0.702194
25%       0.164174
50%       0.458805
75%       1.218945
max      14.264052
Name: pct_change_at_max_date, dtype: float64

In [19]:
selected_investments.sort_values('pct_change')

,ticker,calendardate,pct_change,pct_change_at_max_date,close,close_max,marketcap,marketcap_quantile
7734,QBTS,2025-06-30,0.399155,0.291667,14.64,19.04,3.044633e+09,129365753.5
4603,GROY,2025-06-30,0.404873,0.995475,2.21,6.66,2.642553e+08,129365753.5
854,AENT,2025-06-30,0.437870,0.758621,3.77,10.50,2.862700e+08,129365753.5
10411,URG,2025-06-30,0.448137,0.495238,1.05,3.27,2.491716e+08,129365753.5
7938,RBLX,2025-06-30,0.452137,-0.359316,105.20,134.72,4.680162e+10,129365753.5
4503,GPCR,2025-06-30,0.480930,2.043877,20.74,74.30,1.543120e+09,129365753.5
3324,ECG,2025-06-30,0.496731,0.872973,63.53,76.76,3.123214e+09,129365753.5
816,ADUR,2025-06-30,0.604605,0.251116,8.96,10.74,1.312472e+08,129365753.5
3862,EU,2025-06-30,0.620103,-0.262238,2.86,4.94,3.278199e+08,129365753.5
5720,KMTS,2025-06-30,0.633496,0.344391,16.58,25.70,1.258042e+09,129365753.5
5817,KRMN,2025-06-30,0.640056,0.963073,50.37,50.47,3.987707e+09,129365753.5
1382,AMPX,2025-06-30,0.692507,1.980998,4.21,12.94,3.001597e+08,129365753.5
8854,SEPN,2025-06-30,0.972341,1.727058,10.57,27.09,4.509304e+08,129365753.5
7898,RAPP,2025-06-30,0.994839,1.580475,11.37,29.23,3.886990e+08,129365753.5
10382,UPB,2025-06-30,1.106006,-0.289617,10.98,27.39,4.416463e+08,129365753.5
9340,SNDK,2025-06-30,1.111983,12.209702,45.35,56.42,4.983296e+09,129365753.5
3238,DVS,2025-06-30,1.271227,0.393491,3.38,3.67,2.027746e+08,129365753.5
6226,LION,2025-06-30,1.314171,0.623064,5.81,8.15,2.065744e+09,129365753.5
11691,ZBIO,2025-06-30,1.412616,1.664603,9.69,25.68,4.074649e+08,129365753.5
9051,SION,2025-06-30,1.924312,0.992507,17.35,25.00,5.692047e+08,129365753.5

In [17]:
(selected_investments['pct_change_at_max_date'] < 0).sum()

np.int64(3)

In [18]:
(investments['pct_change_at_max_date'] < 0).sum()

np.int64(4)

In [13]:
investments[investments.ticker != 'ABVX'].pct_change_at_max_date.describe()

count    19.000000
mean      1.451818
std       2.865397
min      -0.702194
25%       0.175608
50%       0.623064
75%       1.622539
max      12.209702
Name: pct_change_at_max_date, dtype: float64